### ISSUE TITLE
(linux) Warning: Kaleido is not available on this system. Julia will be unable to save images of any plots.

### ISSUE THREAD

**Issue by anj00** [sglyon/PlotlyBase.jl#45] opened 2021-04-06 18:51 UTC
In my linux container (based on official julia 1.6.0 image) I get the following error
```
Warning: Kaleido is not available on this system. Julia will be unable to save images of any plots.
@ PlotlyBase ~/.julia/packages/PlotlyBase/4zBf6/src/kaleido.jl:64
Warning: ErrorException("Could not start Kaleido process")
PlotlyBase ~/.julia/packages/PlotlyBase/4zBf6/src/kaleido.jl:65
```

As I understand it should had been fixed already [#40](https://github.com/sglyon/PlotlyBase.jl/issues/40) but I seem to still get it
Looking at the log of installed packages, I see the correct one is installed (`PlotlyBase v0.5.1`)
```
  [f0f68f2c] + PlotlyJS v0.14.1
    Updating `~/.julia/environments/v1.6/Manifest.toml`
  [bf4720bc] + AssetRegistry v0.1.0
  [9e28174c] + BinDeps v1.0.2
  [ad839575] + Blink v0.12.5
  [de31a74c] + FunctionalCollections v0.5.0
  [9fb69e20] + Hiccup v0.2.2
  [97c1335a] + JSExpr v0.5.2
  [50d2b5c4] + Lazy v0.15.1
  [ffc61752] + Mustache v1.0.10
  [a975b10e] + Mux v0.7.5
  [510215fc] + Observables v0.3.3
  [fa939f87] + Pidfile v1.2.0
  [a03496cd] + PlotlyBase v0.5.1
  [f0f68f2c] + PlotlyJS v0.14.1
  [0f1e0344] + WebIO v0.8.15
  [104b5d7c] + WebSockets v1.5.9
  [cc8bc4a8] + Widgets v0.6.2
  [f7e6163d] + Kaleido_jll v0.1.0+0
  [7b1f6079] + FileWatching
```

**Comment by anj00** [comment] 2021-04-06 19:04
exact setup. This is headless (no graphical screen) client (=docker container) in case it is related

```
~/code# julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.6.0 (2021-03-24)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(@v1.6) pkg> st
      Status `~/.julia/environments/v1.6/Project.toml`
  [4f1ea46c] AWSCore v0.6.17 ⚲
  [0d499d91] AWSSDK v0.5.0 ⚲
  [3e78a19a] Bukdu v0.4.16 ⚲
  [336ed68f] CSV v0.8.4 ⚲
  [a93c6f00] DataFrames v0.22.7 ⚲
  [864edb3b] DataStructures v0.18.9 ⚲
  [01fcc997] FTPClient v1.2.1 ⚲
  [5789e2e9] FileIO v1.6.5 ⚲
  [59287772] Formatting v0.4.2 ⚲
  [708ec375] Gumbo v0.8.0 ⚲
  [cd3eb016] HTTP v0.9.5 ⚲
  [033835bb] JLD2 v0.4.3 ⚲
  [682c06a0] JSON v0.21.1 ⚲
  [429524aa] Optim v1.3.0 ⚲
  [f0f68f2c] PlotlyJS v0.14.1 ⚲
  [91a5bcdd] Plots v1.11.2 ⚲
  [2dfb63ee] PooledArrays v1.2.1 ⚲
  [2913bbd2] StatsBase v0.33.4 ⚲
  [f269a46b] TimeZones v1.5.3 ⚲
  [ea10d353] WeakRefStrings v0.6.2 ⚲
  [228000da] XMLDict v0.4.1 ⚲

julia> using PlotlyJS
┌ Warning: Kaleido is not available on this system. Julia will be unable to save images of any plots.
└ @ PlotlyBase ~/.julia/packages/PlotlyBase/4zBf6/src/kaleido.jl:64
┌ Warning: ErrorException("Could not start Kaleido process")
└ @ PlotlyBase ~/.julia/packages/PlotlyBase/4zBf6/src/kaleido.jl:65

julia> versioninfo()
Julia Version 1.6.0
Commit f9720dc2eb (2021-03-24 12:55 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
Environment:
  JULIA_GPG = 3673DF529D9049477F76B37566E3C7DC03D6E495
  JULIA_VERSION = 1.6.0
  JULIA_PATH = /usr/local/julia
```

**Comment by anj00** [comment] 2021-04-08 09:05
I tried to manually run the kaleido start command outside julia in my container
`/root/.julia/artifacts/c4c64afe6e141b2663324e1848349cdc49296b41/kaleido plotly --disable-gpu`
what I get in the output (don't understand why stdout nor stderr doesn't catch it in kaleido.jl)
```
[0408/084508.003045:WARNING:resource_bundle.cc(435)] locale_file_path.empty() for locale 
[0408/084508.003561:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
```

So the solution for me (docker, julia:1.6.0 image, linux) is to modify line line 35 in kaleido.jl from this
`Sys.isapple() ? `$(cmd) plotly --disable-gpu --single-process` : `$(cmd) plotly --disable-gpu``
to this
```
no_sanbox = Sys.islinux() && (String(read(`whoami`)) == "root\n") ? "--no-sandbox" : ""
Sys.isapple() ? `$(cmd) plotly --disable-gpu --single-process` : `$(cmd) plotly --disable-gpu $(no_sanbox)`
```

**Comment by panbroggi** [comment] 2021-04-08 11:49
Hi!
Same problem here on Linux (KaOS) using the official binary release.
```
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.6.0 (2021-03-24)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> using PlotlyJS
┌ Warning: Kaleido is not available on this system. Julia will be unable to save images of any plots.
└ @ PlotlyBase ~/.julia/packages/PlotlyBase/4zBf6/src/kaleido.jl:64
┌ Warning: ErrorException("Could not start Kaleido process")
└ @ PlotlyBase ~/.julia/packages/PlotlyBase/4zBf6/src/kaleido.jl:65

julia> versioninfo()
Julia Version 1.6.0
Commit f9720dc2eb (2021-03-24 12:55 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 4

(@v1.6) pkg> st
      Status `~/.julia/environments/v1.6/Project.toml`
  [28b8d3ca] GR v0.57.2
  [f0f68f2c] PlotlyJS v0.14.1
  [91a5bcdd] Plots v1.11.2
```

and running `` ~/.julia/artifacts/c4c64afe6e141b2663324e1848349cdc49296b41/bin/kaleido plotly --disable-gpu`` doesn't work. Adding the ``--no-sandbox`` option I get

```
[0408/134035.867223:WARNING:resource_bundle.cc(435)] locale_file_path.empty() for locale 
[0408/134035.876300:WARNING:resource_bundle.cc(435)] locale_file_path.empty() for locale 
[0408/134035.876315:WARNING:resource_bundle.cc(435)] locale_file_path.empty() for locale 
[0408/134035.883033:WARNING:dns_config_service_posix.cc(341)] Failed to read DnsConfig.
{"code": 0, "message": "Success", "result": null, "version": "0.1.0"}
[0408/134035.894487:WARNING:resource_bundle.cc(435)] locale_file_path.empty() for locale 
[0408/134035.897169:WARNING:dns_config_service_posix.cc(341)] Failed to read DnsConfig.
```

and the prompt cursor blinks, which means that it is working; or is it not?

Applying your suggestions to ``kaleido.jl `` doesn't solve the issue.

**Comment by panbroggi** [comment] 2021-04-09 08:36
After a bit of reading, the problem is that I need the ``--no-sandbox`` flag even if I'm not root. This means that replacing ``line 35`` of ``kaleido.jl`` with
```
no_sandbox = Sys.islinux() ? "--no-sandbox" : ""
Sys.isapple() ? `$(cmd) plotly --disable-gpu --single-process` : `$(cmd) plotly --disable-gpu $(no_sandbox)`
```
leads to a successful precompilation.

This has something to do with a kernel policy and is probably the same reason one normally needs to set the rights of ``chrome-sandbox`` with ``chmod 4755 chrome-sandbox``. However, this doesn't work on kaleido.

**Comment by sglyon** [comment] 2021-04-09 13:05
Thank you for finding this! Would you be willing to create a pull request with the change?

**Comment by panbroggi** [comment] 2021-04-09 16:02
I'm happy to help! I created the pull request. Let me know if everything is fine - it's the fist time I create a pull request, actually.

**Comment by sglyon** [comment] 2021-04-09 19:14
Thank you -- just merged!

**Comment by PetrKryslUCSD** [comment] 2021-06-15 21:16
I just found this error on windows. Again. With julia 1.6,
  [682c06a0] JSON v0.21.1                                                      
  [47be7bcc] ORCA v0.5.0                                                    
  [f0f68f2c] PlotlyJS v0.14.1   
Setting the permissions for kaleido.exe so that the user could execute fixed the problem.

**Comment by sglyon** [comment] 2021-07-24 18:27
Kaleido support moved to PlotlyJS.jl -- if this is still an ongoing issue, please re-open there. 

Thanks!

**Closed by sglyon** 2021-07-24 18:27 UTC
